### ISSUE TITLE
Link project name and folder name?

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1872] opened 2022-11-15 08:39 UTC
Hi folks,

Very often we have different versions of a project, usually created by copying the project folder and pasting it into a new folder. However, doing this doesn't change the name of the project even if the new folder name is different. So, in my recent projects list I get something like the below. I know that if you hover over each entry you do get a very helpful tooltip with the actual path - but I wonder, do we want a stronger link between the project name and the actual folder name?

![image](https://user-images.githubusercontent.com/7080191/201870221-f30ddd20-7f27-42e1-82bf-246e104f9d8b.png)

**Comment by PekkaSavolainen** [comment] 2022-11-15 08:50
Duplicate of https://github.com/Spine-project/Spine-Toolbox/issues/1818. Will be handled in the near future.

**Closed by PekkaSavolainen** 2022-11-15 08:50 UTC
Labels: enhancement
