### ISSUE TITLE
Exception and unpredictable behaviour after additional data

### ISSUE THREAD

**Issue by jimhommes** [Spine-project/Spine-Toolbox#1432] opened 2021-06-07 09:27 UTC
I'm experiencing some unpredictable behaviour. Unfortunately because of confidentiality I can't share data or the project, but I'll describe it as best I can.

In my project today I got some additional data and inserted it into the Excel sheets for which I have created Imports in Spine. No additional columns and such: just data. Mind you that some are quite extensive (e.g. 60k+ rows)

When running the Imports after first inserting the data I got this exception:
```
Traceback (most recent call last):
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spine_engine\utils\returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spine_items\importer\do_work.py", line 56, in do_work
    table_mappings, table_options, table_column_convert_specs, table_row_convert_specs, max_rows=-1
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spinedb_api\spine_io\importers\reader.py", line 103, in get_mapped_data
    data_source, mappings, header, table, column_convert_fns, row_convert_fns
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 124, in get_mapped_data
    _make_parameter_values(mapped_data)
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 228, in _make_parameter_values
    row[value_pos] = _parameter_value_from_dict(value)
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 238, in _parameter_value_from_dict
    return _table_to_map(d["data"], compress=d.get("compress", False))
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 251, in _table_to_map
    d = _table_to_dict(table)
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 267, in _table_to_dict
    d[row[-2]] = row[-1]
TypeError: 'str' object does not support item assignment
```

I figured that maybe a column was switched or datatype changed due to the new data and inspected the imports. This is where the unpredictable part starts: the previews were sometimes showing different (might be old) data from a certain point onwards (see screenshot).

![python_2021-06-07_11-13-11-053_ZBWRdwqc9l](https://user-images.githubusercontent.com/5991344/120992020-79519e00-c782-11eb-9368-b89c9cc724a2.png)

I've seen this happen in other sheets where the datatypes were conflicting, but it's a hard to reproduce as it's unpredictable. The Excel file does not show this data, and after switching sheets the preview showed the correct data. It might be a caching problem of sorts? 

I feel that the problems might be linked, that's why I'm posting this as one package. Any help would be appreciated! For the record: I've pulled latest and everytime I've also upgraded through pip.

**Comment by jimhommes** [comment] 2021-06-07 09:55
I've found that empty values in my Excel files were not truly empty, they contained a string break which caused both the exception and the behavior in the preview. In the screenshot the original data had 84 lines, and from there on the string breaks which were showing data from other sheets (or old data? Abritrary anyway)

**Comment by jkiviluo** [comment] 2021-06-08 07:39
Good catch. Just to clarify, do you mean line break by the string break?

How to make this better is then harder. There could be a number of ways this goes wrong. @manuelma @soininen Would it be possible to at least pinpoint the cell where the problem starts? That may make it easier for the user to really go look into that cell and think about the error message (which is not all bad).

**Comment by manuelma** [comment] 2021-06-08 07:52
@jimhommes, would it be possible for you to provide a excel file that has the offending character, or exposes the issues to a certain extent? I understand is not fully deterministic, but if you have something that 'likely' reproduces the bug it would be a great help.

Another question. I understand the table is sometimes showing 'old' data. Does this happen when switching tables (sheets)?

>  it be possible to at least pinpoint the cell where the problem starts? 

Most probably yes @jkiviluo. I like your idea for an initial solution.

**Comment by jimhommes** [comment] 2021-06-08 11:11
I managed to create an Excel file in a small project. I'm only unable to recreate the behavior in the preview there.
[issue_test.zip](https://github.com/Spine-project/Spine-Toolbox/files/6615954/issue_test.zip)

The importer does fail but with a different exception however, 
```
Traceback (most recent call last):
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spine_engine\utils\returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spine_items\importer\do_work.py", line 56, in do_work
    table_mappings, table_options, table_column_convert_specs, table_row_convert_specs, max_rows=-1
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spinedb_api\spine_io\importers\reader.py", line 103, in get_mapped_data
    data_source, mappings, header, table, column_convert_fns, row_convert_fns
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 124, in get_mapped_data
    _make_parameter_values(mapped_data)
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 228, in _make_parameter_values
    row[value_pos] = _parameter_value_from_dict(value)
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 238, in _parameter_value_from_dict
    return _table_to_map(d["data"], compress=d.get("compress", False))
KeyError: 'data'
```

The Excel file contains the "line breaks", they are created when exporting from MS Access. In Excel, if you use "Go to Special" and select "Blanks" you will see that the empty cells are not selected, as they contain this illegal character. 

Switching tables sometimes in the importer makes it appear, sometimes disappear.

**Comment by manuelma** [comment] 2021-06-10 07:45
Thanks @jimhommes I see the traceback. Will fix that now.

How do I make the entries appear and disappear? I am in the Importer spec editor, and I am selecting Sheet1 and then Sheet3 (and back), what am I supposed to see exactly?

**Comment by manuelma** [comment] 2021-06-10 08:28
Hi @jimhommes 

I pushed a fix for the above traceback to spinedb_api's master. Can you give it a shot whenever you get the chance?

It turns out that the special characters were successfully interpreted as Python's None, but the treatment of those None's was a little off on our side. I'm hoping this fix can also help with the original traceback, otherwise we'll need a way to reproduce that one with public data.

The third part of this issue, i.e. values appearing and disappearing in the Import editor, remains open. The bare minimum to start tackling it is a procedure where the behavior is reproduced at least with a 50% likelihood. Can we achieve that?

**Comment by jimhommes** [comment] 2021-06-11 08:00
I've pulled and tried to run the project I uploaded but I get the following exception:

```
Process ReturningProcess-1:
Traceback (most recent call last):
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spine_engine\utils\returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spine_items\importer\do_work.py", line 56, in do_work
    table_mappings, table_options, table_column_convert_specs, table_row_convert_specs, max_rows=-1
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spinedb_api\spine_io\importers\reader.py", line 103, in get_mapped_data
    data_source, mappings, header, table, column_convert_fns, row_convert_fns
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 124, in get_mapped_data
    _make_parameter_values(mapped_data)
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 228, in _make_parameter_values
    row[value_pos] = _parameter_value_from_dict(value)
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 238, in _parameter_value_from_dict
    return _table_to_map(d["data"], compress=d.get("compress", False))
KeyError: 'data'
```

I feel like the third issue happens with lots of data, and I might have something that will reproduce it:
[issue_test2.zip](https://github.com/Spine-project/Spine-Toolbox/files/6636768/issue_test2.zip)

I've imported the some larger sheets from MS Access and replaced the data. There is a sheet AAA and a sheet BBB filled with only these strings. Now, if you enter the importer and first explore sheet AAA for a bit (so scroll down and right for a while), and afterwards do the same with sheet BBB, you'll see that the BBB sheet starts showing AAA values. Then switching between sheets makes it disappear and reappear but arbitrarily.

**Comment by manuelma** [comment] 2021-06-11 08:28
Hi @jimhommes 

thanks very much for trying it out. Just one question: Which dataset/project do you get the traceback with? Is it the same you sent last time, or is it the new one?

**Comment by jimhommes** [comment] 2021-06-11 08:33
I got the traceback with the old project - afterwards I altered it to see if I could get the reappearing numbers, but haven't tried to run it again. I imagine the new project will give the same traceback after in the importer the new sheets are disabled.

**Comment by manuelma** [comment] 2021-06-11 08:45
Thanks @jimhommes 

I don't get the traceback with the new project. I get two maps correctly imported in the output db. Can you try upgrading all requirements again? Something's off here...

**Comment by manuelma** [comment] 2021-06-11 09:28
I don't see the issues about cross-contamination of values across sheets. I tried both on Linux and on Windows virtual machine.

Can anybody else give it a try? @soininen @PekkaSavolainen ?

All you need to do is follow the instructions by @jimhommes here https://github.com/Spine-project/Spine-Toolbox/issues/1432#issuecomment-859367684

**Comment by jimhommes** [comment] 2021-06-11 09:38
I upgraded everything without change, after uninstalling all packages and reinstalling them it seems to have done the trick. I now run the importer successfully and have no more occurrences of the cross-contamination.

**Comment by soininen** [comment] 2021-06-11 09:40
I also gave this a spin but didn't notice anything unusual in the preview tables.

**Comment by manuelma** [comment] 2021-06-11 09:43
Thanks! @jimhommes there's still the first traceback in the original post. Can we reproduce that one? Whenever you get the chance, no rush. Your help has been super valuable so far.

**Comment by jimhommes** [comment] 2021-06-11 12:11
I'm not getting that specific traceback anymore. It was produced the same way as the other traceback, just by running the import. I'm presuming it's fixed?

**Comment by manuelma** [comment] 2021-06-11 12:15
It's possible that it got fixed while fixing the other one. If you're happy with how it works at the moment, we can close this?

I'm still worried that running the upgrade process didn't update all the requirements for you. Maybe we need another issue for that @soininen @PekkaSavolainen ? I believe it's not the first time you @jimhommes need to uninstall plus reinstall to see changes.

**Closed** 2021-06-11 12:25 UTC
