### ISSUE TITLE
Importer numbering relationship dimension entities in headers

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1783] opened 2022-10-03 08:51 UTC
Importer adds an automatic number to objects that appear more than once. It's a problem when the object is just a dimension in a relationship and is not therefore a duplicate. This probably happens only when those objects are in the header row. CSV has a forced first row header, so there is no work-around. (I would also like that CSV did not have forced header row, but that's another issue).

![image](https://user-images.githubusercontent.com/40472544/193537232-a0cf2658-c2d8-4aa3-9ffb-6f2f616af0f3.png)

**Comment by soininen** [comment] 2022-10-03 09:21
Just to be precise: the forced headers are due to using datapackage and not a CSV reader feature.

**Comment by soininen** [comment] 2022-10-04 05:43
It is possible to refer to a column by its header instead of column number when specifying import mappings and column headers must be unique for that to work. That is why Importer adds the extra number to duplicate column names.

A quick workaround would be to add a dummy header to such files that makes the pivot object names part of the non-header data. I'll have a look if we can make the datapackage header optional - it really does not make with pivoted data.

**Comment by soininen** [comment] 2022-10-04 12:08
Closing as duplicate of #1730

**Closed by soininen** 2022-10-04 12:08 UTC
