### ISSUE TITLE
Exporter: entity class, parameter name selection for each mapping

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1260] opened 2021-03-05 07:31 UTC
Currrently, Exporter exports all data available in a database. However, users may want a mapping to work only on certain entity classes or parameter names. This could be achieved e.g. by adding a Selection column to the mapping table. The column could be filled for object class, relationship class and parameter definition rows. Possible values would be '*' to select all items and a comma separated list database item names.

**Comment by manuelma** [comment] 2021-03-05 13:03
We could also do the filtering in another item as it's been discussed previously I think.

**Comment by soininen** [comment] 2021-03-05 13:06
Each mapping may (and probably will!) have different selection. I don't see how we could do that in a separate item.

**Comment by manuelma** [comment] 2021-03-06 16:15
You're right. It's the same as for the 'default' excel export, we want each object class mapped to a different sheet, rather than all object classes in one sheet.

However, the filter needs to be easy to specify through the UI. I'm thinking a reg exp can do the job nicely. The empty string would mean 'all pass' in this case. And then, entering a parameter or class name would filter the corresponding 'column' by that name.

I will try something out if you don't mind...

**Comment by soininen** [comment] 2021-03-08 07:03
Isn't regular expression an overkill here? Do we expect users to learn the syntax? Why not go with the original idea of using `*` to select all and besides that, accept a comma separated list of name?

Something like regular expression might be useful in case of object names if somebody wanted to select e.g. all nodes with `FIN_` in their names, but even then I would consider having a simplified syntax like `FIN_*`.

**Comment by manuelma** [comment] 2021-03-08 07:22
how is `FIN_*` simplified compared to `FIN_`? 

But you're right, we should use whatever suits our users. Regular expressions are easy if you don't need to go fancy, so that's why I went with it.

Also, if we introduce an alternative syntax, we can (and perhaps should) use the regexp engine that's already in place in the backend, because is as fast as it gets.

**Comment by soininen** [comment] 2021-03-08 07:49
I had to go and look how the regular expressions for the use cases we discussed with @jkiviluo would look like: `node|unit` doesn't actually look that bad as long as you remember not to add any spaces there. Perhaps my opposition to regexes stems from the fact that when I have had to use them I needed to create very complex expressions. I think we should keep them for now and add a cheat sheet for the most regular ones in the specification editor.

**Comment by manuelma** [comment] 2021-03-08 07:53
`unit|node` looks ok, yeah, the problem is when you need it case insensitive for example, that can get a bit uglier.

**Comment by soininen** [comment] 2021-03-08 08:02
There is an `IGNORECASE` flag in `re`. Perhaps we should always enable it?

**Comment by manuelma** [comment] 2021-03-08 08:05
Didn't know about `IGNORECASE`, yeah, that's a good idea.

Spine-project/Spine-Database-API#118 is more challenging if we want to make it a subcase of this. What about taking a different approach for that one?

**Comment by soininen** [comment] 2021-03-08 08:09
> What about taking a different approach for that one?

I was thinking of using the 'filter' cell to filter by value type, too so all selections would be set up the same way. This would need some special syntax that is distinct from regexp, though. What do you have in mind?

**Comment by manuelma** [comment] 2021-03-08 08:16
Ok, so something like `value=time|map` that lets pass time-series, time-patterns and maps for instance, could be good. In principle I'd also want something that lets pass e.g. 2d maps but filers out all 1d and (3+)d maps...

**Comment by manuelma** [comment] 2021-03-08 08:21
Another idea is to introduce a new `Mapping` subclass, say `ValueTypeMapping` that yields value types and filters the children by that type. In this case I could send the `ValueTypeMapping` to the table name position and have each type in a different row.

**Comment by soininen** [comment] 2021-03-08 08:25
I think we need ways of selecting values both by their type and dimension.

`ValueTypeMapping` (and perhaps `ValueDimensionMapping` sound very interesting ideas. I encourage you to explore that design space more.

**Comment by jkiviluo** [comment] 2021-03-08 09:10
If I try to edit the filter, I loose the previous content.

**Comment by jkiviluo** [comment] 2021-04-01 13:32
> ValueTypeMapping (and perhaps ValueDimensionMapping) sound very interesting ideas. I encourage you to explore that design space more.

Me too. Just needed this functionality. Currently, I need to go around it by creating more entity classes for no other purpose. Or then I need to have separate names for the mapped parameters and unmapped parameters and use REGEX filter on parameter names (which mean I need to list every possible parameter name since REGEX does not support NOT - at least not in an easy way).

**Comment by jkiviluo** [comment] 2021-04-01 13:42
BTW, as a first order of approximation, we could just assume that parameters with wrong dimensionality would not be output.

E.g. 'node' object class contains parameters:
demand[node, time]
demandAnnual[node]

If you use the exporter to export parameters with two dimensions (1 object dimension and 1 map index dimension), you only get `demand` and if you export parameters with one dimension (1 object dimension), then you get only `demandAnnual`.

**Comment by manuelma** [comment] 2021-04-01 15:23
ParameterValueTypeMapping is implemented in spinedb_api side, and used in the excel export functionality within Spine DB Editor. I guess we can bring it in the Exporter spec editor next.

**Comment by jkiviluo** [comment] 2021-04-04 06:47
I made a new issue about that: https://github.com/Spine-project/Spine-Toolbox/issues/1352

We can close this now (I will link to the end of this discussion though).

**Closed by jkiviluo** 2021-04-04 06:47 UTC
Labels: Project items, enhancement
