### ISSUE TITLE
SQLAlchemy thread crash

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1794] opened 2022-10-11 15:45 UTC
When opening multiple maps at once from the DB editor, I got this. Maybe related to: 3e2e3d2d3929c591d9d3fb39b261390c9cffa82e

```
(spi38) C:\data\SpineToolbox>python spinetoolbox.py
Traceback (most recent call last):
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\base.py", line 1204, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\default.py", line 821, in _init_compiled
    self.cursor = self.create_cursor()
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\default.py", line 1188, in create_cursor
    return self._dbapi_connection.cursor()
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\pool\base.py", line 1000, in cursor
    return self.connection.cursor(*args, **kwargs)
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 24340 and this is thread id 25396.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\base.py", line 749, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\default.py", line 558, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 24340 and this is thread id 25396.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\base.py", line 749, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\default.py", line 558, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 24340 and this is thread id 25396.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\data\SpineToolbox\spinetoolbox\helpers.py", line 1600, in run
    self._result = self._fn(*self._args, **self._kwargs)
  File "C:\data\SpineToolbox\spinetoolbox\spine_db_worker.py", line 300, in _get_parameter_value_metadata
    return self._db_map.query(sq).filter(sq.c.parameter_value_id == parameter_value_id).all()
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\orm\query.py", line 3373, in all
    return list(self)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\orm\query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\orm\query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\base.py", line 1206, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\base.py", line 1505, in _handle_dbapi_exception
    self._autorollback()
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\util\langhelpers.py", line 82, in __exit__
    compat.raise_(value, with_traceback=traceback)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\base.py", line 1505, in _handle_dbapi_exception
    self._autorollback()
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\base.py", line 888, in _autorollback
    self._root._rollback_impl()
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\base.py", line 751, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\base.py", line 1505, in _handle_dbapi_exception
    self._autorollback()
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\util\langhelpers.py", line 82, in __exit__
    compat.raise_(value, with_traceback=traceback)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\base.py", line 1505, in _handle_dbapi_exception
    self._autorollback()
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\base.py", line 888, in _autorollback
    self._root._rollback_impl()
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\base.py", line 751, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\base.py", line 1405, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\base.py", line 749, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\site-packages\sqlalchemy\engine\default.py", line 558, in do_rollback
    dbapi_connection.rollback()
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 24340 and this is thread id 25396.
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Comment by manuelma** [comment] 2022-10-12 06:49
Thank you, will try to reproduce.

**Comment by jkiviluo** [comment] 2022-10-12 07:57
I first had one map open, which I kept open. They I opened another map (which is then opened to another window). I think that creates the issue quite reliably. I'm getting similar traceback also when trying to add objects.

**Comment by Tasqu** [comment] 2022-10-12 08:10
I'm guessing this is a broader issue. I occasionally get similar tracebacks when importing/exporting via the DB Editor, committing changes, or removing objects. I haven't found a way to reproduce any particular issue reliably, but it seems the problems get more frequent with larger DBs, as I can't get e.g. SpineOpt template to break.

**Comment by jkiviluo** [comment] 2022-10-12 08:42
My DB is not big. Each map contained 1 full year time series. However, it's not reproducing right now (which is good so that I get work done).

**Comment by jkiviluo** [comment] 2022-10-12 08:45
But now I did something else and it crashed with the thread traceback again. I was in the middle of adding a parameter, but went and tried to open the drop-down of another object class to see object names.

**Comment by jkiviluo** [comment] 2022-10-12 08:46
I should also say that while this maybe happened before occasionally, now it's happening all the time (probably that commit mentioned).

**Comment by manuelma** [comment] 2022-10-12 09:32
I just reverted the problematic commit. Will apply it to a branch to experiment.

**Comment by jkiviluo** [comment] 2022-10-12 16:59
I don't see anything systematic (although I first thought so with the maps). However, I didn't need to do much in the DB editor before a crash came. Opening things, selecting items, adding new objects...

**Comment by manuelma** [comment] 2022-10-13 09:49
It seems to work better in the feature branch after some changes. I made a clear mistake which was to assume that QThreadPool with maxThreadCount forced to 1 would always use the same QThread to run things. That seems to not be the case, QThreadPool seems to allow itself to destroy a thread and replace it by another at any point in time. That of course should lead to the first reported traceback. I don't know which is the second one, the so-called 'thread traceback' - but if it was leading to a crash, possibly is due to us inadvertendly doing some UI work from the DB thread...

**Comment by jkiviluo** [comment] 2022-10-13 12:05
Great. I'll test when I can, probably over the weekend.

**Comment by manuelma** [comment] 2022-10-18 11:30
The original TB is gone so I'm closing this. I will open another issue for the ocassional crash.

**Closed** 2022-10-18 11:33 UTC
