### ISSUE TITLE
System Settings window can't be enlarged

### ISSUE THREAD

**Issue by mdandreadtu** [Spine-project/Spine-Toolbox#3] opened 2019-06-28 14:43 UTC
The size of the system settings window can't be enlarged and the current size makes it hard to use.

**Comment by PekkaSavolainen** [comment] 2019-06-28 15:13
The size of the Settings windows is fixed on purpose. What makes it hard to use and would enlarging it even help in this regard?

**Comment by mdandreadtu** [comment] 2019-07-01 10:13
![syssetting](https://user-images.githubusercontent.com/51364710/60427939-13ecee00-9bf8-11e9-8250-0531da8f8cfe.PNG)
![fullscreenshot](https://user-images.githubusercontent.com/51364710/60427941-13ecee00-9bf8-11e9-9c07-cc0194b0cf5d.PNG)
 Hey, @PekkaSavolainen as you can see the left part of the setting window isn't shown completely. It would be better if the windows would be large enough to display it entirely. Also the font of the text in the white boxes is quite small. Hope It was helpful :)

**Comment by PekkaSavolainen** [comment] 2019-08-05 13:59
Ok, the Settings window is definitely not intended to look like that. The problem is caused by the scaling of your display. Eg. on Win10 right click on your desktop and select Display settings. There you can play with the scale and layout of your displays. If you set the scale to 100%, the Settings window should look like this.

![issue#3_on_github_settings_window](https://user-images.githubusercontent.com/43600314/62470014-1f58a980-b7a2-11e9-82a1-b520f3b21be5.png)

I'll see what can be done about this problem.

**Comment by PekkaSavolainen** [comment] 2019-08-05 14:56
Fixed in 'dev' branch. Settings window is now resizable. The whole Settings window will be redesigned at some point so I hope this helps until then.

**Closed** 2019-08-28 11:30 UTC
Labels: bug
