### ISSUE TITLE
Tracekback when upening second Spine Toolbox

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1819] opened 2022-11-02 11:54 UTC
I had SpineToolbox running with TradeRES project (executing workflow). When I opened another Spine Toolbox from separate Anaconda prompt, I got the traceback below (Toolbox did start and seems to work).

```
(spi38) C:\data\SpineToolbox>python spinetoolbox.py
Process Process-2:
Process Process-1:
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\data\SpineToolbox\src\spinedb-api\spinedb_api\spine_db_server.py", line 97, in _do_work
    with Listener(self._address) as listener:
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\connection.py", line 446, in __init__
    self._listener = PipeListener(address, backlog)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\connection.py", line 645, in __init__
    self._handle_queue = [self._new_handle(first=True)]
  File "C:\data\SpineToolbox\src\spinedb-api\spinedb_api\spine_db_server.py", line 97, in _do_work
    with Listener(self._address) as listener:
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\connection.py", line 658, in _new_handle
    return _winapi.CreateNamedPipe(
PermissionError: [WinError 5] Access is denied
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\connection.py", line 446, in __init__
    self._listener = PipeListener(address, backlog)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\connection.py", line 645, in __init__
    self._handle_queue = [self._new_handle(first=True)]
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\connection.py", line 658, in _new_handle
    return _winapi.CreateNamedPipe(
PermissionError: [WinError 5] Access is denied
```

**Comment by manuelma** [comment] 2022-11-03 10:08
Will fix. The issue is the second toolbox tries to set up the ordering manager process but it is already setup by the first toolbox. The second toolbox is still able to use the same manager as the first, so everything should work as normal (is it not the case?).

The only small problem is closing the first toolbox will shutdown the ordering manager making the second toolbox unusable (but closing the second won't affect the first).

Anyways, will fix asap.

**Closed** 2022-11-03 10:54 UTC

**Comment by jkiviluo** [comment] 2022-11-03 11:09
Thanks. Indeed, it was working fine (never closed in that problematic order).
