### ISSUE TITLE
Exporter: Output filename saving problem

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1380] opened 2021-04-22 14:39 UTC
When there's more than one Data Store connected to an Exporter, in Exporter properties only the first filename is saved when saving the project. The other filenames are blank after reopening the project.

Maybe related to #1379.

**Comment by soininen** [comment] 2021-04-23 05:45
This was caused by how we reconstruct a project nowadays and should be fixed now. It also prompted me add a feature I have had in my mind for quite some time, namely that Exporter need not immediately 'forget' output filenames of disconnected databases.

**Closed by soininen** 2021-04-23 05:45 UTC
Labels: bug

**Comment by PekkaSavolainen** [comment] 2021-04-23 06:09
Ok, I see what the problem was. Works great now, thanks.
