### ISSUE TITLE
Don't scroll row and column headers in pivot view

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1737] opened 2022-06-29 21:10 UTC
If there are a lot of rows and/or columns you very quickly lose sight of the row and/or column headers maiking it difficult to edit the data. I feel it would be expected behavior for the header rows and columns to be static.

**Comment by manuelma** [comment] 2022-10-28 08:12
Duplicate of https://github.com/Spine-project/Spine-Toolbox/issues/1757

**Closed by manuelma** 2022-10-28 08:12 UTC
Labels: enhancement, Spine database editor
