### ISSUE TITLE
Toolbox `is_active` functionality

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1513] opened 2021-09-16 13:16 UTC
As described in https://github.com/Spine-project/SpineOpt.jl/issues/392 the objective here is to be able to use toolbox tool/feature/method functionality to control object activity within a datastore by using tool/feature/method filtering on the arrow.

So the idea here is:
 - we define a feature for every object class, say `is_active`
 - We define a tool called, say `object_activity_control`
 - We define a tool->feature for every `is_active` feature and the `object_activity_control` tool
 - We define a tool->feature->method of "True" for each tool->feature

The idea now is that if we specify the value `false` for the `is_active` parameter of any object and we have enabled the `object_activity_control` tool filter in our workflow, then that object will not be included.

I was hoping that I would only need to set the value to false to exclude an object and rely on the default value of "True" for the `is_active` parameters so that I wouldn't need to explicitly set a value of `True` for each and every object. However, toolbox and the tool filter functionality don't _know_ about parameter defaults at present (currently handled by SpineInterface for SpineOpt).

Another question is this - we would like this to work in combination with scenarios and scenario filter. So if in Scenario A `is_active=true` for a certain object and in Scenario B `is_active=false`, then we want the relevant object only to be included in Scenario A... so can the scenario filters and tool filters work together like this?

I believe @manuelma has a solution for the first issue but can we confirm if it will play nice with scenarios/alternatives also?

**Comment by manuelma** [comment] 2021-09-16 15:26
This works. The default value is now taken into account if no value is specified for the parameter value (or if it has the value None).

It also works with scenario filters: the scenario filter is applied before the tool filter, which leads to the desired functionality. Please reopen if no good.

**Comment by DillonJ** [comment] 2021-09-16 16:40
I tested this with my db and it's not working for me - I'm getting error messages suggesting that no objects are passing. I sent the DB via slack.

User error is a very strong possibility here.

**Comment by manuelma** [comment] 2021-09-16 17:17
I suggest you not to call `run_spineopt` with the url, just call `using_spinedb` and then the appropriate convenience functions to see the outcome of the filter. That can be much easier to diagnose.

**Comment by DillonJ** [comment] 2021-09-16 20:57
Ok, so trying this. One problem I think was that I was only selectively executing the RunSpineOpt tool rather than the entire workflow (not sure if this was a problem).

I'm getting the following tracebacks (possibly not connected to each other) :

```
Traceback (most recent call last):
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\widgets\project_item_drag.py", line 464, in _change_spec_data
    button = self.widgetForAction(self._actions[row])
KeyError: 0
Traceback (most recent call last):
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\mvcmodels\filter_execution_model.py", line 55, in data
    return list(self._item.filter_log_documents.keys())[index.row()]
IndexError: list index out of range
```

**Comment by DillonJ** [comment] 2021-09-16 21:22
OK so after more testing, I see that the object_activity_control filter works correctly on the objects in that the one I'm trying to exclude is actually excluded but it seems that all relationships in the db are excluded along with it. Not just for the excluded object... all the relationship convenience functions return empty arrays.

There are other strange things going on not sure if they are related or not:
With the object_activity_control filter enabled, if I run the entire workflow, I get this traceback
```
Traceback (most recent call last):
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\mvcmodels\filter_execution_model.py", line 55, in data
    return list(self._item.filter_log_documents.keys())[index.row()]
IndexError: list index out of range
```
and I see no Julia console output

With the object_activity_control filter enabled, if I selectively run just the RunSpineOpt tool, it runs ok, I see the console output but all the relationships are wiped. I get no traceback this way

**Comment by manuelma** [comment] 2021-09-17 06:39
Thank you @DillonJ !

I think we have two issues here, I will work on the first one (all relationships being filtered out). The IndexError must be some silly mistake, we'll fix that right after.

**Comment by manuelma** [comment] 2021-09-17 09:44
The filter should work well now. It excludes the objects and *only* the relationships involving any of those objects.

I can't reproduce the IndexError @DillonJ , can you please provide more details? What's your workflow like? Maybe share a project? (zip project folder shared here works)

**Comment by DillonJ** [comment] 2021-09-17 10:18
It's working now - thanks so much @manuelma I'm really delighted to have this functionality, it's really powerful!

I have added the tool->feature->methods to the template.

Two nice additional steps would be:
 - Syntax to implement the filter when running without toolbox
 - Auto/default application of the object_activity_control filter when detected?

Thoughts?

Thanks again!!!!!

**Comment by manuelma** [comment] 2021-09-17 11:35
I propose we close this and open new ones for improvements. We could repurpose this one but it's good to let us know that the first implementation is working by closing this issue.

**Comment by manuelma** [comment] 2021-09-17 11:36
Continues in https://github.com/Spine-project/Spine-Toolbox/issues/1517

**Closed by manuelma** 2021-09-17 11:35 UTC
Labels: Data
