### ISSUE TITLE
DB editor: copy pasting a "large" parameter value does not work

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1343] opened 2021-03-28 08:48 UTC
Trying to copy-paste a map value from one object parameter value field to another object's parameter value field does not appear to work. Nothing changes.

**Comment by manuelma** [comment] 2021-03-29 06:37
I couldn't reproduce this as follows:

1. Open Db editor, right click on a value cell, select Edit, select map, accept the default map (key => 0)
2. The word `Map` appears now in the cell.
3. Select the cell, copy, go to another cell, paste. It works both in pivot and stacked tables.

What am I missing?

**Comment by soininen** [comment] 2021-03-29 06:58
> What am I missing?

I believe @jkiviluo is talking about copy pasting Maps between cells in the Object/Relationship parameter value table in the tables of DB editor itself, not in Parameter value editor.

**Comment by manuelma** [comment] 2021-03-29 07:00
That's exactly what I'm doing. Let me clarify it in the steps.

**Comment by soininen** [comment] 2021-03-29 07:17
I must have misread the the steps. Sorry for the noise!

**Comment by jkiviluo** [comment] 2021-03-29 11:15
Yes, I guess we are in the same place:

![image](https://user-images.githubusercontent.com/40472544/112828676-b4f02d80-9098-11eb-85e6-958b6dd2df02.png)

However, when I do that and copy a Map with data to another cell, that cell will not have the original data (when I open and look).

**Comment by manuelma** [comment] 2021-03-29 11:31
It's funny, it works flawlessly here. I copy, paste, the open the value I just pasted with the Parameter value editor and see the right data... Maybe somebody else could try and check? What about copy/pasting time-series, or other types of values?

**Comment by jkiviluo** [comment] 2021-03-29 13:28
Copy-pasting single value works fine.

**Comment by jkiviluo** [comment] 2021-03-29 13:30
I realize I get this traceback:

```
Traceback (most recent call last):
  File "c:\data\spinetoolbox\spinetoolbox\spine_db_editor\widgets\spine_db_editor.py", line 409, in paste
    call_on_focused_widget(self, "paste")
  File "c:\data\spinetoolbox\spinetoolbox\helpers.py", line 808, in call_on_focused_widget
    return method()
  File "c:\data\spinetoolbox\spinetoolbox\helpers.py", line 110, in new_function
    return func(*args, **kwargs)
  File "c:\data\spinetoolbox\spinetoolbox\widgets\custom_qtableview.py", line 111, in paste
    return self.paste_normal()
  File "c:\data\spinetoolbox\spinetoolbox\widgets\custom_qtableview.py", line 166, in paste_normal
    data = self._read_pasted_text(text)
  File "c:\data\spinetoolbox\spinetoolbox\widgets\custom_qtableview.py", line 126, in _read_pasted_text
    for row in reader:
_csv.Error: field larger than field limit (131072)
```

I don't see the undo message.

**Comment by soininen** [comment] 2021-03-29 13:31
Can you paste the Map to a text editor or just to a comment field here?

**Comment by jkiviluo** [comment] 2021-03-29 13:44
It's 8760. Pastes into Notepad++,

**Comment by manuelma** [comment] 2021-03-29 14:17
Thanks @jkiviluo that makes sense, I was trying with very small maps. Will try with larger ones and see what happens. Should be easy to take it from there.

**Comment by jkiviluo** [comment] 2021-03-29 14:19
That happens with the FlexTool dataset that I've send before and the workflow is available here: https://gitlab.vtt.fi/FlexTool/flextool3/-/issues

**Comment by manuelma** [comment] 2021-03-29 15:08
Thanks very much @jkiviluo that's awesome! I am running the project now and to be honest importer performance is a bit underwhelming... Would be nice to work on that too.

**Comment by manuelma** [comment] 2021-03-29 15:25
This should be better after pulling latest master. I just set the new field limit to the largest long, please let me know how it goes...

**Comment by soininen** [comment] 2021-03-30 06:06
Wow, I honestly didn't expect `csv` module to have such a limit. Nice catch, @manuelma!

**Comment by manuelma** [comment] 2021-03-30 08:19
Thanks @soininen 

Go figure the reasons... Also, the limit is only for reading, not for writing?! I believe this solution is ok and cross-platform, so I will close this issue.

To be clear, we're not dependent on csv for the copy/pasting, we just use it for the nice convenience... So if this bites again in the future we can just write our own csv iterator replacement I guess?

**Closed by manuelma** 2021-03-30 08:19 UTC

**Comment by soininen** [comment] 2021-03-30 08:22
> To be clear, we're not dependent on csv for the copy/pasting, we just use it for the nice convenience...

I chose to use `csv` format for clipboard data for easy interoperability between other software like Excel. We should keep this in mind if we ever have the need to find a replacement.
