### ISSUE TITLE
Specification editors: tabs and apply button

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1278] opened 2021-03-09 07:43 UTC
It is currently possible to open multiple specification editors at once. This can be useful when designing the whole workflow. A further enhancement would be to add possibility for tabs. Currently only ok button gets the changes applied. An apply button would be a nice addition, so that you don't need to close the specification window when you are testing.

Original idea from @manuelma at https://github.com/Spine-project/Spine-Toolbox/issues/1275 

- [x] Tabs for specification editors
- [x] Save action for specification editors

**Comment by soininen** [comment] 2021-03-09 08:05
I'd prefer applying the changes immediately with no need to remember clicking 'Apply'. Instead of 'Apply', we should have a 'Revert changes'  button. 'Cancel' would revert changes and close the tab/editor while Ok would just close.

**Comment by jkiviluo** [comment] 2021-03-09 08:31
I see your point. I'm hesitating, since there is also some value that you know when you 'apply'. When you are changing specs, they are most of the time non-functional in some way and you wouldn't want them to be used then. It's also a messaging thing - you need to know that stuff is applied right away or otherwise you're likely to close the dialog with 'ok'.

**Comment by manuelma** [comment] 2021-03-09 09:18
I don't like writing changes to disk as the user goes. It's not standard, you need to press save in all software to save your changes, otherwise they're in memory. I'd prefer the Save button and a Save action in the hamburger. "Apply" doesn't feel like the right word to me, it should be "Save".

**Comment by jkiviluo** [comment] 2021-03-09 10:05
I think I'm siding with Manuel here (although some of these web-based apps are constant-saving nowadays). I'm ok with Save, Apply or Save and apply. But I prefer a button (with a shortcut - I suppose ctrl-s if it's save). Hamburger is secondary to me, but good to have.

**Comment by manuelma** [comment] 2021-04-21 10:06
The tabs are in place at the moment in master, but it needs some polishing. I'm working on it now.

Basically I want to create a base class for spec editors, to avoid some annoying boiler plate code.

Also, when closing the multi tab editor, one occasionally gets RunTimeErrors: some PySide2 object already deleted, or QThread: destroyed while running. It's not dramatic in the sense the user doesn't see any side effect, but we should do proper clean up in the close event or something.

**Comment by soininen** [comment] 2021-04-21 11:34
- The tabs could have a name, e.g. the item's label if they are associated with one.

> Also, when closing the multi tab editor, one occasionally gets RunTimeErrors: 

One such traceback was caused by Exporter's specification editor that was parent to its undo stack. When the window was closed the undo stack got destroyed (as it should!) but as a side effect it emitted a cleanChanged signal which was still connected to the already-destroyed window. A proper fix was indeed to disconnect the signal in `closeEvent()`.

**Comment by soininen** [comment] 2021-04-21 11:39
Can we drop the 'window' word from the editor window titles? It is superfluous in my opinion. E.g. "Importer specification editor window" -> "Importer specification editor"

**Comment by manuelma** [comment] 2021-04-21 11:52
> The tabs could have a name, e.g. the item's label if they are associated with one

The tabs are named after the spec. Is that not working? I was thinking that we could add the item name to the status bar, what do you think?

**Comment by soininen** [comment] 2021-04-21 11:59
> The tabs are named after the spec. Is that not working?

At least with Exporter and a brand new specification, the tab name is not updated when I change the specification's name.

> I was thinking that we could add the item name to the status bar, what do you think?

Maybe. I guess the item mostly interesting when there is some item-specific data available for the specification editor, e.g. database for preview in Exporter or database items for 'template creation' in DT.

**Comment by manuelma** [comment] 2021-04-21 18:46
Seems to work better now. No tracebacks at closing.

**Comment by manuelma** [comment] 2021-04-21 18:47
The tab name is only updated when the spec is saved, not every time the name is changed in the line edit. I think it's better this way?

**Comment by soininen** [comment] 2021-04-22 05:02
> The tab name is only updated when the spec is saved, not every time the name is changed in the line edit. I think it's better this way?

I missed that the tab gets renamed only after saving. To be honest it feels a bit confusing to me. Some suggestions:

- Could we come up with a better tab name for a new specification? 'New tab' -> '<anonymous>' or similar that would 1. hint that the tab name is the specification's name 2. remind the users that they need to give the specification a name
- Maybe we should experiment with keeping the tab name updated with the 'name' field? There is still the asterix `*` hinting for unsaved changes
- How about dropping the *Name* line edit and changing the specification's name directly from the tab?

I am somewhat unsure if these improve the situation. Maybe it just takes time to adjust?

**Comment by manuelma** [comment] 2021-04-22 07:15
> Maybe we should experiment with keeping the tab name updated with the 'name' field? There is still the asterix * hinting for unsaved changes

Let's try this one, seems good. Thanks for the ideas!

**Comment by manuelma** [comment] 2021-04-22 07:28
> How about dropping the Name line edit and changing the specification's name directly from the tab?

This one is also interesting but maybe too much? Let's see.

**Comment by soininen** [comment] 2021-04-22 07:33
> This one is also interesting but maybe too much? Let's see.

I agree it may not be obvious enough. I was just throwing out ideas to see what sticks.

**Closed** 2021-04-22 21:11 UTC
