### ISSUE TITLE
Toolbox fails to start after installation for specific python version

### ISSUE THREAD

**Issue by iasonask** [Spine-project/Spine-Toolbox#1645] opened 2022-01-28 11:31 UTC
When using Python 3.8.0 64-bit on Windows 10, the installation succeeds (all dependencies are in place) but Spine-Toolbox (both master and development versions) fails to start.

![image](https://user-images.githubusercontent.com/14200722/151539206-7cf39ff6-cf0b-4d9e-a7f3-d8273cffd3e6.png)

**Comment by PekkaSavolainen** [comment] 2022-01-28 12:31
Confirmed! There seems to be some issue in PySide2 specifically on Python 3.8.0 and Windows 10. Master branch Spine Toolbox seems to start on Python 3.8.1 (and later) without hiccups. I think we should disallow installation on Python 3.8.0 to fix this.

**Comment by PekkaSavolainen** [comment] 2022-01-28 13:01
Yeah, the tracks seem to point to Python 3.8.0 release itself so PySide2 is probably not the only affected package. The problem had something to do with DLL library loading on Windows it was fixed in Python 3.8.1. 

The fix applied here was to disallow installation of Spine Toolbox and Spine Items on Python 3.8.0

**Closed** 2022-01-28 13:02 UTC
Labels: bug, Python support

**Comment by iasonask** [comment] 2022-01-28 13:29
Would it also be helpful to mention it in the installation instructions on the README file?
