### ISSUE TITLE
Value editor assumes time series when copy pasting

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1342] opened 2021-03-28 08:43 UTC
I'm trying to copy paste from excel into a map in the value editor a key - value set like this:
t0000 0
t0001 1
t0002 2

When I copy paste, it gets turned into this:
![image](https://user-images.githubusercontent.com/40472544/112746874-9287e280-8fba-11eb-8d20-9cbe75a79747.png)

It may sometimes nice to be able to do something like that (although it should be done with separate tools), however, it shouldn't be a default. I don't know what is that 'convert leaves to time series' and how it is affecting this. At least there is no visible way to control it. I can click that button, but nothing happens (maybe it should be a checkbox - it's either on or off?).

**Comment by soininen** [comment] 2021-03-29 06:30
This is a duplicate of #1108

**Closed by soininen** 2021-03-29 06:30 UTC
