### ISSUE TITLE
Specification saving issues

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1361] opened 2021-04-09 08:05 UTC
Things that don't work at least in Exporter:

- Clicking OK in the specification editor does not write the specification to disk which I find confusing. Further, there is no way to write the specification if the editor is reopened unless changes are made. No warnings are shown if the specification differs from what is on the disk when closing the Toolbox or project
- Clicking Save does not trigger resource update on Design view. You can close the editor with Cancel only afterwards and this naturally doesn't trigger the update either.

**Comment by manuelma** [comment] 2021-04-09 08:11
Does this happen with the other specification editors?

**Comment by soininen** [comment] 2021-04-09 08:19
> Does this happen with the other specification editors?

I haven't checked yet as I am working on something else at the moment.

**Comment by jkiviluo** [comment] 2021-04-09 08:32
At least some of it applies to other spec editors. It would be comforting to have Ctrl-S to save the spec even when you keep it open. I don't like that I need to close it in order to test the execution of the item.

**Comment by manuelma** [comment] 2021-04-09 08:38
> At least some of it applies to other spec editors

What specifically? I can look into it.

> It would be comforting to have Ctrl-S to save the spec

What about the 'Save' button? You can also activate it by pressing Alt+S.

**Comment by manuelma** [comment] 2021-04-09 09:42
> Clicking OK in the specification editor does not write the specification to disk which I find confusing

It seems to work for me. The specification is written to disk, a message also appears in Event log about this action. What am I missing?

**Comment by soininen** [comment] 2021-04-09 09:46
> What am I missing?

It looks like some special case: saving does not work when adding a fixed header to a mapping.

**Comment by manuelma** [comment] 2021-04-09 10:02
`Specification.is_equivalent()` returns `True` for some reason.

**Comment by PekkaSavolainen** [comment] 2021-04-09 11:01
How about QKeySequence.Save as the shortcut for all the Save buttons in spec editors (and elsewhere).

**Comment by manuelma** [comment] 2021-04-09 11:50
> How about QKeySequence.Save as the shortcut for all the Save buttons in spec editors (and elsewhere).

I mean, do we need Ctrl+S if we already have Alt+S?

**Comment by soininen** [comment] 2021-04-09 11:54
Alt-S? Every software I use uses Ctrl-S for saving.

**Comment by PekkaSavolainen** [comment] 2021-04-09 11:57
> Alt-S? Every software I use uses Ctrl-S for saving.

The tip for using QKeySequence.Save was my way of saying this same thing.

**Comment by manuelma** [comment] 2021-04-09 11:59
It's because Alt+S is the hotkey for the Save button. It already comes with the button. My preference would be to remove the button bar entirely and use menu actions, and then I would support Ctrl+S. But otherwise, it feels too funny.

**Comment by manuelma** [comment] 2021-04-09 12:31
Yeah, so now we're looking at standard frontend design. How weird is to have a main window with a button bar, as we do in the spec editor? Do you think we can get rid of it, and add the same actions to the sandwich menu?

**Comment by jkiviluo** [comment] 2021-04-09 13:00
I don't know much about standards, but it would be nice to be consistent across Toolbox. This is what I would expect at this point (given other programs I'm familiar with and what I've gotten used to in Toolbox):

- Ctrl-S would save but not close. Any menu item or button that does that, should say 'Save (ctrl-s)'.
- Ctrl-Enter would also save but not close. It's meant for 'commit' in DB editor, but in case of spec editor, I would expect the same thing.
- Ctrl+F4 (could also be Ctrl-W) would close current window or tab. If unsaved, it would ask to confirm (but you can turn that warning off and it just saves). Any menu item or button that does that, should say 'Save and close (ctrl-F4)'.
- Alt+F4 would close all tabs and close the editor (I guess right now just DB editor has multiple tabs).
- Esc would escape from e.g. current text edit without changing anything.
- This list does not have 'exit without saving'. Maybe we want that, but it should require a double shortcut. E.g. Ctrl-F4 and then you can confirm to 'exit without saving' by clicking it, or by navigating into it by pressing 'tab' and then 'enter'.

Then the user can learn into good habits.

**Comment by PekkaSavolainen** [comment] 2021-04-09 13:11
Agree with everything on @jkiviluo list above but we do have `exit without saving`. It's essentially what the `Cancel` buttons do and should continue to do. Maybe I'm missing something here, though.

**Comment by manuelma** [comment] 2021-04-09 14:03
What about getting rid of the button bar in spec editors?

**Comment by PekkaSavolainen** [comment] 2021-04-09 14:53
I'm not a fan of getting rid of the ok, save and cancel buttons. The hamburger is easy to miss. The buttons should be regular QPushButtons or QToolButtons if the Button bar buttons do not support changing the shortcut key.

**Comment by manuelma** [comment] 2021-04-09 14:59
> The hamburger is easy to miss

You think so? In the Spine DB Editor we don't have any buttons and people seem to get around ok though...

**Comment by PekkaSavolainen** [comment] 2021-04-09 15:06
Maybe it's not a big deal after all. The important thing is that the spec editor's are consistent (menus and key shortcuts).

**Comment by manuelma** [comment] 2021-04-09 15:10
> Maybe it's not a big deal after all. The important thing is that the spec editor's are consistent (menus and key shortcuts).

You're right. We also may need a base class for spec editors because there's a lot of repetition at the moment.

**Comment by PekkaSavolainen** [comment] 2021-04-09 15:28
There are three additional specification saving issues related to our mini code editor in Tool spec editor that I've been wondering.

1. If I edit a program file in the tool spec editor and click `Save program file` (or whatever it says) without changing anything in the spec. I need to click Cancel to close the editor window. This feels wrong to me (I want to click Ok in this case).
2. When I edit a tool spec (e.g. change description) and edit a program file and then click Ok. It saves the changes to the spec but not the changes in the program file. Is this intentional?
3. When the mini code editor has the focus, you can save changes to files with Ctrl-s. This does not save the changes in the spec.

**Comment by manuelma** [comment] 2021-04-09 16:16
In my text editor (sublime) I can create so-called projects by selecting certain files and/or folders. This 'project' is saved into a yaml file. Independently of that file, I can edit and save the files in the project. The same logic is applied in the spec editor. The spec json file is equivalent to the IDE project file, and is saved independently of the files it contains.

**Comment by manuelma** [comment] 2021-04-09 16:19
To me the problem is still the button bar. Ok, Cancel, are too vague. If we had actions in a menu, we could be more explicit: Save specification file, Save program file (in the case of the Tool spec editor), Close. Like a normal mainwindow. The spec editor is not a dialog.

**Comment by jkiviluo** [comment] 2021-04-10 13:06
I agree that 'Ok' and 'cancel' are too vague. I don't mind removing them and having them only in the hamburger. I wouldn't mind either if we would have longer, more exploratory names in those buttons. I understand that the spec editors are not dialogs and they maybe shouldn't have those buttons because of that. But both approaches are fine to me, maybe slightly leaning toward removing the buttons. The important thing is to get consistent shortcuts.

> at least in the Tool spec editor's Cancel button is hooked to the Esc key

I guess I don't like that. I'd rather see Esc just as an escape inside the window - not something that closes the window/tab (even if it warns you before doing that).

**Comment by manuelma** [comment] 2021-04-12 18:11
> Clicking OK in the specification editor does not write the specification to disk which I find confusing...

This happens only in exporter and it's not intended. I too would find it confusing if it weren't a bug. But now maybe it's fixed after a commit to `spine_items`.

**Comment by manuelma** [comment] 2021-04-12 18:13
> Clicking Save does not trigger resource update on Design view. You can close the editor with Cancel only afterwards and this naturally doesn't trigger the update either.

This is definitely a miss. I didn't think about it when adding the 'Save' button. Will try to fix it now.

**Comment by manuelma** [comment] 2021-04-12 18:38
I just did the following:
1. Try to fix exporter specification `is_equivalent()` method so the spec is correctly saved to disk after any changes.
2. Reset the spec on the item upon pressing 'Save', so the notifications are refreshed.
3. Don't close the tool spec editor with Esc since it made almost no sense.
4. Open #1366 about getting rid of the button bar.

Not sure if all that is enough to close this one?

**Comment by soininen** [comment] 2021-04-13 05:00
>  what exactly do you mean by 'resource update'? Because saving the spec does not change the resources advertised by the item, does it? I'm guessing you're talking about the exclamation point notifications, rather?

Yes, I meant the exclamation notification. Sorry for the confusion. Clicking the 'Save' button should remove the 'Export specification missing' notification in case of Exporter.

**Comment by soininen** [comment] 2021-04-13 05:10
I'm happy with the fixes. Nice work @manuelma!

**Closed** 2021-05-20 12:23 UTC
Labels: Project items, bug
